version: '3.9'
services:
  db:
    container_name: db-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
